### ISSUE TITLE
userのrouteも複数なのか単数なのか合わせたほうがいい。

### ISSUE THREAD

**Issue by good1luck21** [moonlight4617/blog_app_add_picture#2]
https://github.com/moonlight4617/blog_app_add_picture/blob/29e7e699e71760e999a55d0a6d82afa8f3c5c3bd/config/routes.rb#L30-L33

https://github.com/moonlight4617/blog_app_add_picture/blob/29e7e699e71760e999a55d0a6d82afa8f3c5c3bd/config/routes.rb#L48-L54

**Comment by moonlight4617** [comment]
ありがとうございます。
routeのurlの部分は単一形で統一しました

**Comment by good1luck21** [comment]
ありがとうございます！
